apiVersion: v1
kind: Secret
metadata:
  name: pixabay-apikey
data:
  API_KEY: ASDASDASDASD # Base64 version of apikey provided by pixabay. Create string like this with "echo -n <api-key-here in quotes> | base64" and replate the ASDASD with it