apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-node
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
  template:
    metadata:
      labels:
        app: kube-node
    spec:
      volumes:
        - name: shared-text
          persistentVolumeClaim:
            claimName: logs-claim
      containers:
        - name: kube-node-gateway
          image: PROJECT/GATEWAYIMAGE
          volumeMounts:
            - name: shared-text
              mountPath: /public
          env:
          - name: DEPLOYMENT_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            limits:
              cpu: "100m"
              memory: "50Mi"
        - name: kube-node-backend
          image: PROJECT/BACKENDIMAGE
          envFrom:
          - secretRef:
              name: postgres-credentials
          resources:
            limits:
              cpu: "100m"
              memory: "50Mi"