apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kube-node-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kube-node
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 25