apiVersion: v1
kind: Service
metadata:
  name: ping-pong-service
spec:
  type: ClusterIP # Part 4 uses ClusterIP again
  selector:
    app: ping-pong
  ports:
    - port: 2347
      protocol: TCP
      targetPort: 3002