apiVersion: v1
kind: Service
metadata:
  name: ping-pong-service
spec:
  type: LoadBalancer # This should be the only unfamiliar part
  selector:
    app: ping-pong
  ports:
    - port: 2347
      protocol: TCP
      targetPort: 3002