apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/sealedsecret-postgres.yaml
  - manifests/sealedsecret-telegram.yaml
  - manifests/deployment.yaml
  - manifests/ingress.yaml
  - manifests/namespace-course-exercises.yaml
  - manifests/persistentvolume.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/postgres-statefulset.yaml
  - manifests/service.yaml

images:
  - name: PROJECT/GATEWAYIMAGE
    newName: aventusm/kube-node-project
    newTag: latest
  - name: PROJECT/BACKENDIMAGE
    newName: aventusm/kube-node-project-backend
    newTag: latest
  - name: PROJECT/BROADCASTERIMAGE
    newName: aventusm/kube-node-project-broadcaster
    newTag: latest