apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/rollout.yaml
  - manifests/ingress.yaml
  - manifests/postgres-secret.yaml
  - manifests/service.yaml

images:
  - name: PROJECT/GATEWAYIMAGE
    newName: aventusm/kube-node-project:rollout
  - name: PROJECT/BACKENDIMAGE
    newName: aventusm/kube-node-project-backend