apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/postgres-sealedsecret.yaml
  - manifests/telegram-sealedsecret.yaml
  - manifests/deployment.yaml
  - manifests/ingress.yaml
  - manifests/namespace-course-exercises.yaml
  - manifests/persistentvolume.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/postgres-statefulset.yaml
  - manifests/service.yaml