apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-bot
  namespace: default
spec:
  encryptedData:
    SECRET_TELEGRAM_TOKEN: AgA+99XkiFOocs60hUVQRmPYskBxfOeHDk/2ai/RmOF7v1yek0cDw7D9R9f/wem2grSkWGaWnwxKZDwVDjty7UEedsilqS8be2811ISY0+ERHocOeK0pTbRCXh6O+60Rf5F50qlAQg1BZ63rq7tvtStYvhOtG2qRBd2Hq2O44KaH9++Ysv8WQQ5c2kKC4QOSOy+ggdQKLOFlE6NiOHOAlA0qzXJwm9g4v75r0/AxydGtOVW1s42/NWmkz+iiO7YXc4XddtHl8BknEqBWhBLTOvBlZ7ExSM6lDDCuW/SMcUG5ngTM5AHTPoqxAE1QdXdzArx6/kePNQRYPVecZUTF7YxOqOZSq32JALpKBwwSgUJwJcbzFGuiWAQRSnSDoh0S+QnZQTNoQCchb3xWRpXk1r2vOwXRZYMqV2D3/Q9iwPF2jSZXy/Jqk44wEWIS+rppDaQwqxd7UczFZikBCE13amQeecnsMKdLLPemcL+UoPWL0TBrjNYQu3cDkcXIFkiGI8Btb4QStcpCmn6ZUC0Y3fa7QuvFaBHRXn4tuXr41sPOArPhWiHwXZ+OvVmpf7o920eemseFBwpQpY+rzRvaYF4yyife7E67q7on9BFLLSbY5jASgZEwLL5l5Z3V66cMPnkbS3Jz2oFHRRSJ6imyf0QliX1QKfyz/PdVG2RcfoSnpbDscFRNzSZkimitaUks4OQ1VSUF+IsHDbLh94BfMITgBZVKlGuBVDJwXzyNFOi/6jEMQ9R6Xd2mHeLe+h+K
  template:
    metadata:
      creationTimestamp: null
      name: telegram-bot
      namespace: default

