apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/course-exercises-namespace.yaml
  - manifests/deployment.yaml
  - manifests/ingress.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/postgres-secret.yaml
  - manifests/postgres-statefulset.yaml
  - manifests/service.yaml

images:
  - name: PROJECT/GATEWAYIMAGE
    newName: aventusm/kube-node-project-gke
  - name: PROJECT/BACKENDIMAGE
    newName: aventusm/kube-node-project-backend-gke