apiVersion: apps/v1
kind: Deployment
metadata:
  name: split-timestamp-string
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      volumes: # Define volume
        - name: shared-text
          # emptyDir: {}
          persistentVolumeClaim:
            claimName: logs-claim
      containers:
        - name: timestamp-creator-split
          image: aventusm/timestamp-creator-split
          volumeMounts: # Mount volume
            - name: shared-text
              mountPath: /files
          resources:
            limits:
              cpu: "100m"
              memory: "50Mi"
        - name: timestamp-response
          image: aventusm/timestamp-response
          envFrom:
          - configMapRef:
              name: main-ping-pong-configmap
          volumeMounts: # Mount volume
            - name: shared-text
              mountPath: /files
          resources:
            limits:
              cpu: "100m"
              memory: "50Mi"
          readinessProbe:
            initialDelaySeconds: 10 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /healthz
               port: 3001
