apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: logs-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: logs
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 25