apiVersion: v1
kind: Service
metadata:
  name: split-timestamp-string-service
spec:
  type: NodePort # GKE requirement instead of ClusterIP with Ingresses
  selector:
    app: logs
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3001
