apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: aventusm/ping-pong-http-gke # gke version adds "/pingpong" in the GET requests in the ping-pong project due to 3.2 constraints with PathPrefixStrip
          envFrom:
          - secretRef:
              name: postgres-credentials
