apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: PROJECT/BROADCASTERIMAGE
          env:
            - name: NATS_URL
              value: nats://my-nats:4222
          envFrom:
            - secretRef:
                name: telegram-bot