apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - ingress.yaml
  - namespace-course-exercises.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - sealedsecret-postgres.yaml
  - sealedsecret-telegram.yaml
  - postgres-statefulset.yaml
  - service.yaml

images:
  - name: PROJECT/GATEWAYIMAGE
    newName: aventusm/kube-node-project
    newTag: 5e7dbe06e256b14260dbb5ba74dc045f5e96493f
  - name: PROJECT/BACKENDIMAGE
    newName: aventusm/kube-node-project-backend
    newTag: 5e7dbe06e256b14260dbb5ba74dc045f5e96493f
  - name: PROJECT/BROADCASTERIMAGE
    newName: aventusm/kube-node-project-broadcaster
    newTag: 5e7dbe06e256b14260dbb5ba74dc045f5e96493f